using System.Diagnostics;
using System.Text;

namespace DotnetForge.Core;

public sealed class PackMaterializer(IPackRegistry packRegistry)
{
    public void Materialize(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        Directory.CreateDirectory(paths.DotnetForgeDirectory);

        var files = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var asset in packRegistry.GetSharedAssets())
        {
            files[asset.RelativePath] = asset.Content;
        }

        foreach (var asset in packRegistry.GetPackAssets(configuration.SelectedPack.Id))
        {
            files[asset.RelativePath] = asset.Content;
        }

        foreach (var (relativePath, content) in files)
        {
            var fullPath = Path.Combine(configuration.WorkingDirectory, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            File.WriteAllText(fullPath, content, Encoding.UTF8);
        }

        WriteForgeConfiguration(configuration, paths);
        WriteWrappers(configuration, paths);
    }

    private static void WriteForgeConfiguration(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by dotnet-forge. Edit dotnet-forge.json or use CLI pack commands.");
        builder.AppendLine("# Format: window <role> <agent> <worktree> [task|batch] [extra-cli-args...]");
        foreach (var role in configuration.SelectedPack.Roles)
        {
            builder.Append("window ")
                .Append(role.Name)
                .Append(' ')
                .Append(configuration.AgentBackend)
                .Append(' ')
                .Append(role.Worktree);

            if (role.ReceiveMode == ReceiveMode.Batch)
            {
                builder.Append(" batch");
            }

            if (role.ExtraArgs is { Count: > 0 })
            {
                builder.Append(' ').Append(string.Join(' ', role.ExtraArgs));
            }

            builder.AppendLine();
        }

        File.WriteAllText(Path.Combine(paths.DotnetForgeDirectory, "dotnet-forge.conf"), builder.ToString(), Encoding.UTF8);
    }

    private static void WriteWrappers(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        var scriptsDirectory = Path.Combine(paths.DotnetForgeDirectory, "scripts");
        Directory.CreateDirectory(scriptsDirectory);

        var scripts = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["handoff_queue.sh"] = "handoff queue",
            ["ready_for_next.sh"] = "handoff next",
            ["done_with_current.sh"] = "handoff done",
        };

        foreach (var (name, command) in scripts)
        {
            var path = Path.Combine(scriptsDirectory, name);
            File.WriteAllText(path, BuildShScript(command), Encoding.UTF8);
            TryMakeExecutable(path);
        }

        var closeForge = Path.Combine(configuration.WorkingDirectory, "close-forge.sh");
        File.WriteAllText(closeForge, BuildShScript("stop"), Encoding.UTF8);
        TryMakeExecutable(closeForge);
    }

    private static string BuildShScript(string subCommand)
    {
        return $"dotnet-forge {subCommand} \"$@\"";
    }

    private static void TryMakeExecutable(string path)
    {
        if (OperatingSystem.IsWindows())
        {
            return;
        }

        try
        {
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                                       UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                                       UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
        }
        catch (PlatformNotSupportedException)
        {
        }
    }
}

public sealed class RuntimeStateStore
{
    public IReadOnlyList<RuntimeRole> LoadRoles(string workingDirectory)
    {
        var paths = ProjectPaths.For(workingDirectory);
        if (!File.Exists(paths.RolesFile))
        {
            throw new ForgeException($"Runtime roles file not found: {paths.RolesFile}", 2);
        }

        return File.ReadAllLines(paths.RolesFile)
            .Where(static line => !string.IsNullOrWhiteSpace(line))
            .Select(static line => line.Split('\t'))
            .Select(static fields => new RuntimeRole(
                fields[0],
                fields[1],
                fields[2],
                fields[3],
                fields[4],
                fields[5],
                Enum.TryParse<ReceiveMode>(fields[6], true, out var mode) ? mode : ReceiveMode.Task))
            .ToArray();
    }

    public void Write(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        Directory.CreateDirectory(paths.StateDirectory);
        Directory.CreateDirectory(Path.Combine(paths.StateDirectory, "daemon"));
        Directory.CreateDirectory(paths.PidsDirectory);
        Directory.CreateDirectory(paths.PromptsDirectory);

        var runtimeRoles = configuration.SelectedPack.Roles.Select(role => new RuntimeRole(
            role.Name,
            role.Worktree,
            paths.WorktreePath(role.Worktree),
            $"dotnet-forge-{role.Name}",
            DisplayName(role.Name),
            configuration.AgentBackend,
            role.ReceiveMode)).ToArray();

        File.WriteAllText(
            paths.RolesFile,
            string.Join(Environment.NewLine, runtimeRoles.Select(role => string.Join('\t',
                role.Role,
                role.WorktreeName,
                role.WorktreePath,
                role.Session,
                role.DisplayName,
                role.Agent,
                role.ReceiveMode.ToString().ToLowerInvariant()))) + Environment.NewLine,
            Encoding.UTF8);

        File.WriteAllText(
            paths.SessionsFile,
            string.Join(Environment.NewLine, runtimeRoles.Select((role, index) => string.Join('\t',
                index + 1,
                role.Role,
                role.Session,
                role.DisplayName,
                role.Agent))) + Environment.NewLine,
            Encoding.UTF8);

        foreach (var role in runtimeRoles)
        {
            foreach (var suffix in new[] { "outbox/tmp", "sent", "failed", "inbox/new", "inbox/in_process", "inbox/completed" })
            {
                Directory.CreateDirectory(Path.Combine(role.WorktreePath, ".dotnet-forge", "handoffs", suffix));
            }
        }
    }

    public void SavePid(ProjectPaths paths, string role, int pid)
    {
        Directory.CreateDirectory(paths.PidsDirectory);
        File.WriteAllText(Path.Combine(paths.PidsDirectory, $"{role}.pid"), pid.ToString(), Encoding.UTF8);
    }

    public int? LoadPid(ProjectPaths paths, string role)
    {
        var pidFile = Path.Combine(paths.PidsDirectory, $"{role}.pid");
        if (!File.Exists(pidFile))
        {
            return null;
        }

        return int.TryParse(File.ReadAllText(pidFile, Encoding.UTF8).Trim(), out var pid) ? pid : null;
    }

    public static string DisplayName(string role)
        => string.Join(' ', role.Replace('-', ' ').Replace('_', ' ').Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(static part => char.ToUpperInvariant(part[0]) + part[1..]));
}

public sealed class WorkspacePreparationService(ICommandRunner commandRunner)
{
    public void Prepare(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        EnsureDependency("git");
        EnsureDependency("tmux");
        EnsureDependency(configuration.AgentBackend);
        InitializeRepository(paths);
        EnsureRuntimeIgnore(paths);
        PrepareWorktrees(configuration, paths);
    }

    private void EnsureDependency(string tool)
    {
        // On Windows, 'tmux' is only available inside Git Bash — check via bash
        var shell = OperatingSystem.IsWindows() ? "bash" : "sh";
        var result = commandRunner.Run(shell, ["-lc", $"command -v {tool} >/dev/null 2>&1"], throwOnError: false);
        if (result.ExitCode != 0)
        {
            throw new ForgeException($"'{tool}' is required but was not found on PATH.");
        }
    }

    private void InitializeRepository(ProjectPaths paths)
    {
        if (Directory.Exists(Path.Combine(paths.WorkingDirectory, ".git")))
        {
            return;
        }

        commandRunner.Run("git", ["init", paths.WorkingDirectory]);
        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "branch", "-M", "main"]);

        var gitignore = Path.Combine(paths.WorkingDirectory, ".gitignore");
        if (!File.Exists(gitignore))
        {
            File.WriteAllText(gitignore, ".dotnet-forge/\n.worktrees/\n", Encoding.UTF8);
        }

        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "add", "."]);
        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "-c", "user.name=dotnet-forge", "-c", "user.email=dotnet-forge@localhost", "commit", "-m", "Initial dotnet-forge repository"]);
    }

    private void EnsureRuntimeIgnore(ProjectPaths paths)
    {
        var result = commandRunner.Run("git", ["-C", paths.WorkingDirectory, "rev-parse", "--git-path", "info/exclude"]);
        var excludeRelativePath = string.IsNullOrWhiteSpace(result.StandardOutput) ? Path.Combine(".git", "info", "exclude") : result.StandardOutput;
        var excludeFile = Path.IsPathRooted(excludeRelativePath)
            ? excludeRelativePath
            : Path.Combine(paths.WorkingDirectory, excludeRelativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(excludeFile)!);
        var existing = File.Exists(excludeFile) ? File.ReadAllLines(excludeFile).ToHashSet(StringComparer.Ordinal) : [];
        using var writer = File.AppendText(excludeFile);
        foreach (var line in new[] { ".dotnet-forge/", ".worktrees/" })
        {
            if (existing.Add(line))
            {
                writer.WriteLine(line);
            }
        }
    }

    private void PrepareWorktrees(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        Directory.CreateDirectory(paths.WorktreesDirectory);
        foreach (var role in configuration.SelectedPack.Roles.Where(static role => role.Worktree is not "master" and not "none"))
        {
            var worktreePath = paths.WorktreePath(role.Worktree);
            if (Directory.Exists(Path.Combine(worktreePath, ".git")) || File.Exists(Path.Combine(worktreePath, ".git")))
            {
                continue;
            }

            commandRunner.Run("git", ["-C", paths.WorkingDirectory, "worktree", "add", "--force", "-B", $"dotnet-forge-{role.Worktree}", worktreePath, "HEAD"]);
        }
    }
}

public sealed class AgentLaunchCommandBuilder
{
    public void WritePromptFile(ProjectPaths paths, RuntimeRole role)
    {
        Directory.CreateDirectory(paths.PromptsDirectory);
        var promptFile = Path.Combine(paths.PromptsDirectory, $"{role.Role}.md");
        File.WriteAllText(
            promptFile,
            $"Read dotnet-forge/constitution.prompt, then read every file it refers to recursively, and obey all of those instructions.{Environment.NewLine}" +
            $"Read dotnet-forge/roles/{role.Role}.prompt, then read every file it refers to recursively, and follow all of those instructions.{Environment.NewLine}",
            Encoding.UTF8);
    }

    public (string FileName, IReadOnlyList<string> Arguments) Build(
        RuntimeRole role, string promptFile, ProjectPaths paths)
    {
        var promptText = string.Join(" ", File.ReadAllLines(promptFile, Encoding.UTF8).Select(line => line.Trim())).Trim();
        var scriptsDirectory = Path.Combine(role.WorktreePath, "dotnet-forge", "scripts");

        return role.Agent switch
        {
            "opencode" => (
                FindAgentExecutable("opencode"),
                [role.WorktreePath, "--prompt", promptText]),

            "copilot" => (
                FindAgentExecutable("copilot"),
                ["-C", role.WorktreePath, "--name", $"DotnetForge {role.DisplayName}", "-i", promptText]),

            "claude" => (
                FindAgentExecutable("claude"),
                ["--append-system-prompt-file", promptFile, "--permission-mode", "acceptEdits",
                 "-n", $"DotnetForge {role.DisplayName}", promptText]),

            "codex" => (
                FindAgentExecutable("codex"),
                ["-C", role.WorktreePath, promptText]),

            "grok" => (
                FindAgentExecutable("grok"),
                ["--cwd", role.WorktreePath, "--permission-mode", "acceptEdits", "--rules", promptText, "--verbatim", promptText]),

            _ => throw new ForgeException($"Unsupported agent backend '{role.Agent}'.", 2),
        };
    }

    private static string FindAgentExecutable(string name)
    {
        if (OperatingSystem.IsWindows())
        {
            // Look for npm-installed executables in common global locations
            var appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            var candidateDirs = new[]
            {
                Path.Combine(appData, "npm", "node_modules", $"{name}-ai", "bin"),
                Path.Combine(appData, "npm", "node_modules", name, "bin"),
            };

            foreach (var dir in candidateDirs)
            {
                var exe = Path.Combine(dir, $"{name}.exe");
                if (File.Exists(exe)) return exe;
            }

            // Fallback: let the OS resolve it via PATH
        }
        return name;
    }
}

public sealed class RunOrchestrator(
    EffectiveConfigurationService effectiveConfigurationService,
    PackMaterializer packMaterializer,
    WorkspacePreparationService workspacePreparationService,
    RuntimeStateStore runtimeStateStore,
    AgentLaunchCommandBuilder agentLaunchCommandBuilder,
    HandoffDaemon handoffDaemon,
    ICommandRunner commandRunner)
{
    public async Task<RunSummary> RunAsync(LaunchOptions options, CancellationToken cancellationToken = default)
    {
        var effectiveConfiguration = await effectiveConfigurationService.ResolveAsync(options, cancellationToken);
        var paths = ProjectPaths.For(effectiveConfiguration.WorkingDirectory);
        packMaterializer.Materialize(effectiveConfiguration);
        if (!effectiveConfiguration.DryRun)
        {
            workspacePreparationService.Prepare(effectiveConfiguration);
        }
        runtimeStateStore.Write(effectiveConfiguration);
        var runtimeRoles = runtimeStateStore.LoadRoles(effectiveConfiguration.WorkingDirectory);
        var executedCommands = new List<string>();

        if (!effectiveConfiguration.DryRun)
        {
            if (File.Exists(paths.StopFile))
            {
                File.Delete(paths.StopFile);
            }

            // --- TUI setup (dashboard only) ---
            using var tui = new ForgeTui(runtimeRoles,
                packId: effectiveConfiguration.SelectedPack.Id,
                workingDirectory: effectiveConfiguration.WorkingDirectory);
            tui.Start();
            tui.SetStatusMessage("Launching agents via tmux…");

            // Create tmux socket in /tmp (Unix-compatible filesystem needed for Git Bash).
            // Upstream swarmforge uses /tmp/swarmforge-<user>/<hash>.sock
            var userName = Environment.GetEnvironmentVariable("USERNAME")
                ?? Environment.GetEnvironmentVariable("USER")
                ?? "dotnet-forge";
            var projectHash = Math.Abs(effectiveConfiguration.WorkingDirectory.GetHashCode(StringComparison.Ordinal)).ToString("x8");
            var tmuxSocketDir = $"/tmp/dotnet-forge-{userName}";
            var tmuxSocket = $"{tmuxSocketDir}/{projectHash}.sock";

            // Store socket path for stop/reference
            File.WriteAllText(paths.TmuxSocketFile, tmuxSocket + Environment.NewLine);

            // Create socket dir (Unix-compatible, must exist before tmux can create the socket)
            RunBash($"mkdir -p \"{tmuxSocketDir}\"");

            // Kill any leftover sessions from previous runs
            try { RunTmux($"-S \"{tmuxSocket}\" list-sessions", throwOnError: false); } catch { }

            var delay = effectiveConfiguration.ProjectConfiguration.AgentStartDelayMs;

            for (var index = 0; index < runtimeRoles.Count; index++)
            {
                var role = runtimeRoles[index];
                if (index > 0 && delay > 0)
                {
                    await Task.Delay(delay, cancellationToken);
                }

                agentLaunchCommandBuilder.WritePromptFile(paths, role);
                var (exe, args) = agentLaunchCommandBuilder.Build(role,
                    Path.Combine(paths.PromptsDirectory, $"{role.Role}.md"), paths);

                tui.Trace(role.Role, $"Creating tmux session: {role.Session} in {role.WorktreePath}");

                // Create detached tmux session (routed through bash on Windows)
                RunTmux($"-S \"{tmuxSocket}\" new-session -d -s \"{role.Session}\" -c \"{TmuxHelper.ToUnixPath(role.WorktreePath)}\"");

                // Build the full command to send into the tmux session.
                // Convert Windows paths to Unix-style (/c/Users/...) so bash inside tmux can execute them.
                var unixExe = TmuxHelper.ToUnixPath(exe);
                var argsStr = string.Join(" ", args.Select(a =>
                {
                    var converted = TmuxHelper.ToAbsolutePathArg(a);
                    return converted.Contains(' ') ? $"\"{converted.Replace("\"", "\\\"")}\"" : converted;
                }));
                var fullCmd = $"{unixExe} {argsStr}";
                // Escape for tmux send-keys -l (literal text)
                var literalCmd = fullCmd.Replace("\\", "\\\\").Replace("\"", "\\\"");

                // Send the initial command into the session
                RunTmux($"-S \"{tmuxSocket}\" send-keys -t \"{role.Session}\" -l \"{literalCmd}\"");
                RunTmux($"-S \"{tmuxSocket}\" send-keys -t \"{role.Session}\" Enter");

                executedCommands.Add($"{exe} {string.Join(" ", args)}");
                tui.Trace(role.Role, $"Started tmux session: {role.Session}");
                tui.SetStatus(role.Role, $"running in tmux");
            }

            // Use tmux-based notifier — sends keys directly into agent sessions
            var notifier = new TmuxAgentNotifier(tmuxSocket, commandRunner);

            var daemonCts = new CancellationTokenSource();
            var daemonTask = handoffDaemon.RunAsync(effectiveConfiguration.WorkingDirectory, daemonCts.Token, notifier);

            tui.SetStatusMessage("All agents launched. Monitoring… (dotnet-forge stop to quit)");

            // --- Monitoring loop ---
            try
            {
                while (!cancellationToken.IsCancellationRequested && !File.Exists(paths.StopFile))
                {
                    await Task.Delay(1000, cancellationToken);
                }
            }
            catch (OperationCanceledException) { }

            tui.SetStatusMessage("Shutting down…");

            daemonCts.Cancel();
            try { await daemonTask; } catch (OperationCanceledException) { }

            // Kill all tmux sessions
            foreach (var role in runtimeRoles)
            {
                try
                {
                    RunTmux($"-S \"{tmuxSocket}\" kill-session -t \"{role.Session}\"", throwOnError: false);
                }
                catch { }
            }
        }
        else
        {
            foreach (var role in runtimeRoles)
            {
                agentLaunchCommandBuilder.WritePromptFile(paths, role);
                var (exe, args) = agentLaunchCommandBuilder.Build(role,
                    Path.Combine(paths.PromptsDirectory, $"{role.Role}.md"), paths);
                executedCommands.Add($"{exe} {string.Join(" ", args)}");
            }
        }

        return new RunSummary(effectiveConfiguration, paths, runtimeRoles, executedCommands);
    }

    private void RunTmux(string tmuxArgs, bool throwOnError = true)
    {
        TmuxHelper.Run(commandRunner, tmuxArgs, throwOnError);
    }

    private void RunBash(string command, bool throwOnError = true)
    {
        var shell = OperatingSystem.IsWindows() ? "bash" : "sh";
        commandRunner.Run(shell, ["-c", command], throwOnError: throwOnError);
    }
}

internal static class TmuxHelper
{
    private static string? _drivePrefix;
    private static readonly object _lock = new();

    /// <summary>
    /// Returns "/mnt/" on WSL2 (where C:\ is /mnt/c) or "/" on Git Bash (where C:\ is /c).
    /// Probes via bash so it works from a Windows .NET host calling into WSL bash.
    /// </summary>
    private static string DrivePrefix
    {
        get
        {
            if (_drivePrefix is not null) return _drivePrefix;
            lock (_lock)
            {
                if (_drivePrefix is not null) return _drivePrefix;

                if (!OperatingSystem.IsWindows())
                {
                    _drivePrefix = "";
                    return _drivePrefix;
                }

                try
                {
                    var psi = new System.Diagnostics.ProcessStartInfo("bash", "-c \"test -d /mnt/c && echo wsl\"")
                    {
                        RedirectStandardOutput = true,
                        UseShellExecute = false,
                        CreateNoWindow = true,
                    };
                    using var proc = System.Diagnostics.Process.Start(psi);
                    proc?.WaitForExit(3000);
                    _drivePrefix = proc?.StandardOutput.ReadToEnd().Trim() == "wsl" ? "/mnt/" : "/";
                }
                catch
                {
                    _drivePrefix = "/";
                }

                return _drivePrefix;
            }
        }
    }

    public static void Run(ICommandRunner runner, string tmuxArgs, bool throwOnError = true)
    {
        if (OperatingSystem.IsWindows())
        {
            runner.Run("bash", ["-c", $"tmux {tmuxArgs}"], throwOnError: throwOnError);
        }
        else
        {
            runner.Run("sh", ["-lc", $"tmux {tmuxArgs}"], throwOnError: throwOnError);
        }
    }

    /// <summary>Convert C:\Users\... to /mnt/c/Users/... (WSL) or /c/Users/... (Git Bash).</summary>
    public static string ToUnixPath(string path)
    {
        if (!OperatingSystem.IsWindows() || path.Length < 2 || path[1] != ':') return path;
        return DrivePrefix + char.ToLowerInvariant(path[0]) + path[2..].Replace('\\', '/');
    }

    /// <summary>
    /// If the argument looks like a Windows absolute path (X:\...),
    /// convert it to a Unix path (/mnt/x/... or /x/...). Otherwise return as-is.
    /// </summary>
    public static string ToAbsolutePathArg(string arg)
    {
        if (OperatingSystem.IsWindows()
            && arg.Length >= 3
            && arg[1] == ':'
            && arg[2] == '\\'
            && char.IsLetter(arg[0]))
        {
            return ToUnixPath(arg);
        }
        return arg;
    }
}

public sealed class StopOrchestrator(RuntimeStateStore runtimeStateStore, ICommandRunner commandRunner)
{
    public void Stop(string workingDirectory)
    {
        var paths = ProjectPaths.For(workingDirectory);
        Directory.CreateDirectory(Path.GetDirectoryName(paths.StopFile)!);
        File.WriteAllText(paths.StopFile, string.Empty, Encoding.UTF8);

        // Kill all tmux sessions for this project
        if (File.Exists(paths.TmuxSocketFile))
        {
            var socket = File.ReadAllText(paths.TmuxSocketFile).Trim();
            foreach (var role in runtimeStateStore.LoadRoles(workingDirectory))
            {
                try
                {
                    RunTmux($"-S \"{socket}\" kill-session -t \"{role.Session}\"", throwOnError: false);
                }
                catch { }
            }
        }
    }

    private void RunTmux(string tmuxArgs, bool throwOnError = true)
    {
        TmuxHelper.Run(commandRunner, tmuxArgs, throwOnError);
    }
}
