using System.Diagnostics;
using System.Text;

namespace DotnetForge.Core;

public sealed class PackMaterializer(IPackRegistry packRegistry)
{
    public void Materialize(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        Directory.CreateDirectory(paths.DotnetForgeDirectory);

        var files = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var asset in packRegistry.GetSharedAssets())
        {
            files[asset.RelativePath] = asset.Content;
        }

        foreach (var asset in packRegistry.GetPackAssets(configuration.SelectedPack.Id))
        {
            files[asset.RelativePath] = asset.Content;
        }

        foreach (var (relativePath, content) in files)
        {
            var fullPath = Path.Combine(configuration.WorkingDirectory, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            File.WriteAllText(fullPath, content, Encoding.UTF8);
        }

        WriteForgeConfiguration(configuration, paths);
        WriteWrappers(configuration, paths);
    }

    private static void WriteForgeConfiguration(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by dotnet-forge. Edit dotnet-forge.json or use CLI pack commands.");
        builder.AppendLine("# Format: window <role> <agent> <worktree> [task|batch] [extra-cli-args...]");
        foreach (var role in configuration.SelectedPack.Roles)
        {
            builder.Append("window ")
                .Append(role.Name)
                .Append(' ')
                .Append(configuration.AgentBackend)
                .Append(' ')
                .Append(role.Worktree);

            if (role.ReceiveMode == ReceiveMode.Batch)
            {
                builder.Append(" batch");
            }

            if (role.ExtraArgs is { Count: > 0 })
            {
                builder.Append(' ').Append(string.Join(' ', role.ExtraArgs));
            }

            builder.AppendLine();
        }

        File.WriteAllText(Path.Combine(paths.DotnetForgeDirectory, "dotnet-forge.conf"), builder.ToString(), Encoding.UTF8);
    }

    private static void WriteWrappers(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        var scriptsDirectory = Path.Combine(paths.DotnetForgeDirectory, "scripts");
        Directory.CreateDirectory(scriptsDirectory);

        var scripts = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["handoff_queue.cs"] = "handoff queue",
            ["ready_for_next.cs"] = "handoff next",
            ["done_with_current.cs"] = "handoff done",
        };

        foreach (var (name, command) in scripts)
        {
            var path = Path.Combine(scriptsDirectory, name);
            File.WriteAllText(path, BuildCsScript(command), Encoding.UTF8);
            TryMakeExecutable(path);
        }

        var closeForge = Path.Combine(configuration.WorkingDirectory, "close-forge.cs");
        File.WriteAllText(closeForge, BuildCsScript("stop"), Encoding.UTF8);
        TryMakeExecutable(closeForge);
    }

    private static string BuildCsScript(string subCommand)
    {
        var args = subCommand.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var argsLiteral = string.Join(", ", args.Select(a => $"\"{a}\""));
        return $$"""
            #!/usr/bin/env -S dotnet run
            using System.Diagnostics;
            var psi = new ProcessStartInfo("dotnet-forge") { UseShellExecute = false };
            foreach (var a in new[] { {{argsLiteral}} }.Concat(args)) psi.ArgumentList.Add(a);
            var p = Process.Start(psi) ?? throw new InvalidOperationException("Failed to start dotnet-forge");
            p.WaitForExit();
            return p.ExitCode;
            """;
    }

    private static void TryMakeExecutable(string path)
    {
        if (OperatingSystem.IsWindows())
        {
            return;
        }

        try
        {
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                                       UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                                       UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
        }
        catch (PlatformNotSupportedException)
        {
        }
    }
}

public sealed class RuntimeStateStore
{
    public IReadOnlyList<RuntimeRole> LoadRoles(string workingDirectory)
    {
        var paths = ProjectPaths.For(workingDirectory);
        if (!File.Exists(paths.RolesFile))
        {
            throw new ForgeException($"Runtime roles file not found: {paths.RolesFile}", 2);
        }

        return File.ReadAllLines(paths.RolesFile)
            .Where(static line => !string.IsNullOrWhiteSpace(line))
            .Select(static line => line.Split('\t'))
            .Select(static fields => new RuntimeRole(
                fields[0],
                fields[1],
                fields[2],
                fields[3],
                fields[4],
                fields[5],
                Enum.TryParse<ReceiveMode>(fields[6], true, out var mode) ? mode : ReceiveMode.Task))
            .ToArray();
    }

    public void Write(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        Directory.CreateDirectory(paths.StateDirectory);
        Directory.CreateDirectory(Path.Combine(paths.StateDirectory, "daemon"));
        Directory.CreateDirectory(paths.PidsDirectory);
        Directory.CreateDirectory(paths.PromptsDirectory);

        var runtimeRoles = configuration.SelectedPack.Roles.Select(role => new RuntimeRole(
            role.Name,
            role.Worktree,
            paths.WorktreePath(role.Worktree),
            $"dotnet-forge-{role.Name}",
            DisplayName(role.Name),
            configuration.AgentBackend,
            role.ReceiveMode)).ToArray();

        File.WriteAllText(
            paths.RolesFile,
            string.Join(Environment.NewLine, runtimeRoles.Select(role => string.Join('\t',
                role.Role,
                role.WorktreeName,
                role.WorktreePath,
                role.Session,
                role.DisplayName,
                role.Agent,
                role.ReceiveMode.ToString().ToLowerInvariant()))) + Environment.NewLine,
            Encoding.UTF8);

        File.WriteAllText(
            paths.SessionsFile,
            string.Join(Environment.NewLine, runtimeRoles.Select((role, index) => string.Join('\t',
                index + 1,
                role.Role,
                role.Session,
                role.DisplayName,
                role.Agent))) + Environment.NewLine,
            Encoding.UTF8);

        foreach (var role in runtimeRoles)
        {
            foreach (var suffix in new[] { "outbox/tmp", "sent", "failed", "inbox/new", "inbox/in_process", "inbox/completed" })
            {
                Directory.CreateDirectory(Path.Combine(role.WorktreePath, ".dotnet-forge", "handoffs", suffix));
            }
        }
    }

    public void SavePid(ProjectPaths paths, string role, int pid)
    {
        Directory.CreateDirectory(paths.PidsDirectory);
        File.WriteAllText(Path.Combine(paths.PidsDirectory, $"{role}.pid"), pid.ToString(), Encoding.UTF8);
    }

    public int? LoadPid(ProjectPaths paths, string role)
    {
        var pidFile = Path.Combine(paths.PidsDirectory, $"{role}.pid");
        if (!File.Exists(pidFile))
        {
            return null;
        }

        return int.TryParse(File.ReadAllText(pidFile, Encoding.UTF8).Trim(), out var pid) ? pid : null;
    }

    public static string DisplayName(string role)
        => string.Join(' ', role.Replace('-', ' ').Replace('_', ' ').Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(static part => char.ToUpperInvariant(part[0]) + part[1..]));
}

public sealed class WorkspacePreparationService(ICommandRunner commandRunner)
{
    public void Prepare(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        EnsureDependency("git");
        EnsureDependency(configuration.AgentBackend);
        InitializeRepository(paths);
        EnsureRuntimeIgnore(paths);
        PrepareWorktrees(configuration, paths);
    }

    private void EnsureDependency(string tool)
    {
        var result = commandRunner.Run("sh", ["-lc", $"command -v {tool} >/dev/null 2>&1"], throwOnError: false);
        if (result.ExitCode != 0)
        {
            throw new ForgeException($"'{tool}' is required but was not found on PATH.");
        }
    }

    private void InitializeRepository(ProjectPaths paths)
    {
        if (Directory.Exists(Path.Combine(paths.WorkingDirectory, ".git")))
        {
            return;
        }

        commandRunner.Run("git", ["init", paths.WorkingDirectory]);
        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "branch", "-M", "main"]);

        var gitignore = Path.Combine(paths.WorkingDirectory, ".gitignore");
        if (!File.Exists(gitignore))
        {
            File.WriteAllText(gitignore, ".dotnet-forge/\n.worktrees/\n", Encoding.UTF8);
        }

        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "add", "."]);
        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "-c", "user.name=dotnet-forge", "-c", "user.email=dotnet-forge@localhost", "commit", "-m", "Initial dotnet-forge repository"]);
    }

    private void EnsureRuntimeIgnore(ProjectPaths paths)
    {
        var result = commandRunner.Run("git", ["-C", paths.WorkingDirectory, "rev-parse", "--git-path", "info/exclude"]);
        var excludeRelativePath = string.IsNullOrWhiteSpace(result.StandardOutput) ? Path.Combine(".git", "info", "exclude") : result.StandardOutput;
        var excludeFile = Path.IsPathRooted(excludeRelativePath)
            ? excludeRelativePath
            : Path.Combine(paths.WorkingDirectory, excludeRelativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(excludeFile)!);
        var existing = File.Exists(excludeFile) ? File.ReadAllLines(excludeFile).ToHashSet(StringComparer.Ordinal) : [];
        using var writer = File.AppendText(excludeFile);
        foreach (var line in new[] { ".dotnet-forge/", ".worktrees/" })
        {
            if (existing.Add(line))
            {
                writer.WriteLine(line);
            }
        }
    }

    private void PrepareWorktrees(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        Directory.CreateDirectory(paths.WorktreesDirectory);
        foreach (var role in configuration.SelectedPack.Roles.Where(static role => role.Worktree is not "master" and not "none"))
        {
            var worktreePath = paths.WorktreePath(role.Worktree);
            if (Directory.Exists(Path.Combine(worktreePath, ".git")) || File.Exists(Path.Combine(worktreePath, ".git")))
            {
                continue;
            }

            commandRunner.Run("git", ["-C", paths.WorkingDirectory, "worktree", "add", "--force", "-B", $"dotnet-forge-{role.Worktree}", worktreePath, "HEAD"]);
        }
    }
}

public sealed class AgentLaunchCommandBuilder
{
    public string WritePromptFile(ProjectPaths paths, RuntimeRole role)
    {
        Directory.CreateDirectory(paths.PromptsDirectory);
        var promptFile = Path.Combine(paths.PromptsDirectory, $"{role.Role}.md");
        File.WriteAllText(
            promptFile,
            $"Read dotnet-forge/constitution.prompt, then read every file it refers to recursively, and obey all of those instructions.{Environment.NewLine}" +
            $"Read dotnet-forge/roles/{role.Role}.prompt, then read every file it refers to recursively, and follow all of those instructions.{Environment.NewLine}",
            Encoding.UTF8);
        return promptFile;
    }

    public string Build(RuntimeRole role, string promptFile)
    {
        var scriptsDirectory = Path.Combine(role.WorktreePath, "dotnet-forge", "scripts");
        var basePrefix =
            $"export DOTNET_FORGE_ROLE={Shell.Quote(role.Role)} && " +
            $"export PATH={Shell.Quote(scriptsDirectory)}:$PATH && " +
            $"cd {Shell.Quote(role.WorktreePath)} && ";
        var promptArgument = $"\"$(cat {Shell.Quote(promptFile)})\"";
        var displayName = Shell.Quote($"DotnetForge {role.DisplayName}");

        return role.Agent switch
        {
            "claude" => basePrefix + $"claude --append-system-prompt-file {Shell.Quote(promptFile)} --permission-mode acceptEdits -n {displayName} {promptArgument}",
            "codex" => basePrefix + $"codex -C {Shell.Quote(role.WorktreePath)} {promptArgument}",
            "copilot" => basePrefix + $"copilot -C {Shell.Quote(role.WorktreePath)} --name {displayName} -i {promptArgument}",
            "opencode" => basePrefix + $"opencode run {promptArgument}",
            "grok" => basePrefix + $"grok --cwd {Shell.Quote(role.WorktreePath)} --permission-mode acceptEdits --rules {promptArgument} --verbatim {promptArgument}",
            _ => throw new ForgeException($"Unsupported agent backend '{role.Agent}'.", 2),
        };
    }
}

public sealed class RunOrchestrator(
    EffectiveConfigurationService effectiveConfigurationService,
    PackMaterializer packMaterializer,
    WorkspacePreparationService workspacePreparationService,
    RuntimeStateStore runtimeStateStore,
    AgentLaunchCommandBuilder agentLaunchCommandBuilder,
    HandoffDaemon handoffDaemon)
{
    public async Task<RunSummary> RunAsync(LaunchOptions options, CancellationToken cancellationToken = default)
    {
        var effectiveConfiguration = await effectiveConfigurationService.ResolveAsync(options, cancellationToken);
        var paths = ProjectPaths.For(effectiveConfiguration.WorkingDirectory);
        packMaterializer.Materialize(effectiveConfiguration);
        if (!effectiveConfiguration.DryRun)
        {
            workspacePreparationService.Prepare(effectiveConfiguration);
        }
        runtimeStateStore.Write(effectiveConfiguration);
        var runtimeRoles = runtimeStateStore.LoadRoles(effectiveConfiguration.WorkingDirectory);
        var executedCommands = new List<string>();

        if (!effectiveConfiguration.DryRun)
        {
            if (File.Exists(paths.StopFile))
            {
                File.Delete(paths.StopFile);
            }

            var agentProcesses = new Dictionary<string, (Process Process, StreamWriter StdinWriter)>(StringComparer.Ordinal);
            var delay = effectiveConfiguration.ProjectConfiguration.AgentStartDelayMs;

            for (var index = 0; index < runtimeRoles.Count; index++)
            {
                var role = runtimeRoles[index];
                if (index > 0 && delay > 0)
                {
                    await Task.Delay(delay, cancellationToken);
                }

                var promptFile = agentLaunchCommandBuilder.WritePromptFile(paths, role);
                var command = agentLaunchCommandBuilder.Build(role, promptFile);
                var process = LaunchAgentProcess(command, role.WorktreePath);
                runtimeStateStore.SavePid(paths, role.Role, process.Id);
                agentProcesses[role.Session] = (process, process.StandardInput);
                executedCommands.Add(command);
            }

            var stdinWriters = agentProcesses.ToDictionary(
                kvp => kvp.Key,
                kvp => kvp.Value.StdinWriter,
                StringComparer.Ordinal);
            var notifier = new ProcessAgentNotifier(stdinWriters);

            using var daemonCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            var daemonTask = handoffDaemon.RunAsync(effectiveConfiguration.WorkingDirectory, daemonCts.Token, notifier);

            // Monitor stop file and wait until stopped or cancelled
            try
            {
                while (!cancellationToken.IsCancellationRequested && !File.Exists(paths.StopFile))
                {
                    await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken);
                }
            }
            catch (OperationCanceledException)
            {
                // Cancelled via Ctrl+C or token
            }

            await daemonCts.CancelAsync();
            try { await daemonTask; } catch (OperationCanceledException) { }

            foreach (var (process, _) in agentProcesses.Values)
            {
                try
                {
                    if (!process.HasExited)
                    {
                        process.Kill(entireProcessTree: true);
                    }
                    process.Dispose();
                }
                catch
                {
                    // Best-effort cleanup
                }
            }
        }
        else
        {
            foreach (var role in runtimeRoles)
            {
                var promptFile = agentLaunchCommandBuilder.WritePromptFile(paths, role);
                executedCommands.Add(agentLaunchCommandBuilder.Build(role, promptFile));
            }
        }

        return new RunSummary(effectiveConfiguration, paths, runtimeRoles, executedCommands);
    }

    private static Process LaunchAgentProcess(string shellCommand, string workingDirectory)
    {
        var startInfo = new ProcessStartInfo("sh")
        {
            UseShellExecute = false,
            RedirectStandardInput = true,
            RedirectStandardOutput = false,
            RedirectStandardError = false,
            WorkingDirectory = workingDirectory,
        };
        startInfo.ArgumentList.Add("-lc");
        startInfo.ArgumentList.Add(shellCommand);

        return Process.Start(startInfo)
            ?? throw new InvalidOperationException($"Failed to launch agent process in '{workingDirectory}'.");
    }
}

public sealed class StopOrchestrator(RuntimeStateStore runtimeStateStore)
{
    public void Stop(string workingDirectory)
    {
        var paths = ProjectPaths.For(workingDirectory);
        Directory.CreateDirectory(Path.GetDirectoryName(paths.StopFile)!);
        File.WriteAllText(paths.StopFile, string.Empty, Encoding.UTF8);

        // Attempt to kill any tracked agent processes directly
        if (File.Exists(paths.RolesFile))
        {
            foreach (var role in runtimeStateStore.LoadRoles(workingDirectory))
            {
                var pid = runtimeStateStore.LoadPid(paths, role.Role);
                if (pid is null)
                {
                    continue;
                }

                try
                {
                    var process = Process.GetProcessById(pid.Value);
                    if (!process.HasExited)
                    {
                        process.Kill(entireProcessTree: true);
                    }
                }
                catch
                {
                    // Process may have already exited
                }
            }
        }
    }
}
