using System.Text;

namespace DotnetForge.Core;

public sealed class PackMaterializer(IPackRegistry packRegistry)
{
    public void Materialize(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        Directory.CreateDirectory(paths.SwarmforgeDirectory);

        var files = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var asset in packRegistry.GetSharedAssets())
        {
            files[asset.RelativePath] = asset.Content;
        }

        foreach (var asset in packRegistry.GetPackAssets(configuration.SelectedPack.Id))
        {
            files[asset.RelativePath] = asset.Content;
        }

        foreach (var (relativePath, content) in files)
        {
            var fullPath = Path.Combine(configuration.WorkingDirectory, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            File.WriteAllText(fullPath, content, Encoding.UTF8);
        }

        WriteSwarmConfiguration(configuration, paths);
        WriteWrappers(configuration, paths);
    }

    private static void WriteSwarmConfiguration(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by dotnet-forge. Edit dotnet-forge.json or use CLI pack commands.");
        builder.AppendLine("# Format: window <role> <agent> <worktree> [task|batch] [extra-cli-args...]");
        foreach (var role in configuration.SelectedPack.Roles)
        {
            builder.Append("window ")
                .Append(role.Name)
                .Append(' ')
                .Append(configuration.AgentBackend)
                .Append(' ')
                .Append(role.Worktree);

            if (role.ReceiveMode == ReceiveMode.Batch)
            {
                builder.Append(" batch");
            }

            if (role.ExtraArgs is { Count: > 0 })
            {
                builder.Append(' ').Append(string.Join(' ', role.ExtraArgs));
            }

            builder.AppendLine();
        }

        File.WriteAllText(Path.Combine(paths.SwarmforgeDirectory, "swarmforge.conf"), builder.ToString(), Encoding.UTF8);
    }

    private static void WriteWrappers(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        var scriptsDirectory = Path.Combine(paths.SwarmforgeDirectory, "scripts");
        Directory.CreateDirectory(scriptsDirectory);

        var scripts = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["swarm_handoff.sh"] = "handoff queue",
            ["ready_for_next.sh"] = "handoff next",
            ["done_with_current.sh"] = "handoff done",
        };

        foreach (var (name, command) in scripts)
        {
            var path = Path.Combine(scriptsDirectory, name);
            File.WriteAllText(path, $"#!/usr/bin/env bash\nset -euo pipefail\nexec dotnet-forge {command} \"$@\"\n", Encoding.UTF8);
            TryMakeExecutable(path);
        }

        var closeSwarm = Path.Combine(configuration.WorkingDirectory, "close-swarm");
        File.WriteAllText(closeSwarm, "#!/usr/bin/env bash\nset -euo pipefail\nexec dotnet-forge stop \"$@\"\n", Encoding.UTF8);
        TryMakeExecutable(closeSwarm);
    }

    private static void TryMakeExecutable(string path)
    {
        try
        {
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                                       UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                                       UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
        }
        catch (PlatformNotSupportedException)
        {
        }
    }
}

public sealed class RuntimeStateStore
{
    public IReadOnlyList<RuntimeRole> LoadRoles(string workingDirectory)
    {
        var paths = ProjectPaths.For(workingDirectory);
        if (!File.Exists(paths.RolesFile))
        {
            throw new ForgeException($"Runtime roles file not found: {paths.RolesFile}", 2);
        }

        return File.ReadAllLines(paths.RolesFile)
            .Where(static line => !string.IsNullOrWhiteSpace(line))
            .Select(static line => line.Split('\t'))
            .Select(static fields => new RuntimeRole(
                fields[0],
                fields[1],
                fields[2],
                fields[3],
                fields[4],
                fields[5],
                Enum.TryParse<ReceiveMode>(fields[6], true, out var mode) ? mode : ReceiveMode.Task))
            .ToArray();
    }

    public void Write(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        Directory.CreateDirectory(paths.StateDirectory);
        Directory.CreateDirectory(Path.Combine(paths.StateDirectory, "daemon"));
        Directory.CreateDirectory(paths.PromptsDirectory);

        var runtimeRoles = configuration.SelectedPack.Roles.Select(role => new RuntimeRole(
            role.Name,
            role.Worktree,
            paths.WorktreePath(role.Worktree),
            $"dotnet-forge-{role.Name}",
            DisplayName(role.Name),
            configuration.AgentBackend,
            role.ReceiveMode)).ToArray();

        File.WriteAllText(
            paths.RolesFile,
            string.Join(Environment.NewLine, runtimeRoles.Select(role => string.Join('\t',
                role.Role,
                role.WorktreeName,
                role.WorktreePath,
                role.Session,
                role.DisplayName,
                role.Agent,
                role.ReceiveMode.ToString().ToLowerInvariant()))) + Environment.NewLine,
            Encoding.UTF8);

        File.WriteAllText(
            paths.SessionsFile,
            string.Join(Environment.NewLine, runtimeRoles.Select((role, index) => string.Join('\t',
                index + 1,
                role.Role,
                role.Session,
                role.DisplayName,
                role.Agent))) + Environment.NewLine,
            Encoding.UTF8);

        foreach (var role in runtimeRoles)
        {
            foreach (var suffix in new[] { "outbox/tmp", "sent", "failed", "inbox/new", "inbox/in_process", "inbox/completed" })
            {
                Directory.CreateDirectory(Path.Combine(role.WorktreePath, ".swarmforge", "handoffs", suffix));
            }
        }
    }

    public static string DisplayName(string role)
        => string.Join(' ', role.Replace('-', ' ').Replace('_', ' ').Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(static part => char.ToUpperInvariant(part[0]) + part[1..]));
}

public sealed class WorkspacePreparationService(ICommandRunner commandRunner)
{
    public void Prepare(EffectiveConfiguration configuration)
    {
        var paths = ProjectPaths.For(configuration.WorkingDirectory);
        EnsureDependency("git");
        EnsureDependency("tmux");
        EnsureDependency(configuration.AgentBackend);
        InitializeRepository(paths);
        EnsureRuntimeIgnore(paths);
        PrepareWorktrees(configuration, paths);
    }

    private void EnsureDependency(string tool)
    {
        var result = commandRunner.Run("sh", ["-lc", $"command -v {tool} >/dev/null 2>&1"], throwOnError: false);
        if (result.ExitCode != 0)
        {
            throw new ForgeException($"'{tool}' is required but was not found on PATH.");
        }
    }

    private void InitializeRepository(ProjectPaths paths)
    {
        if (Directory.Exists(Path.Combine(paths.WorkingDirectory, ".git")))
        {
            return;
        }

        commandRunner.Run("git", ["init", paths.WorkingDirectory]);
        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "branch", "-M", "main"]);

        var gitignore = Path.Combine(paths.WorkingDirectory, ".gitignore");
        if (!File.Exists(gitignore))
        {
            File.WriteAllText(gitignore, ".swarmforge/\n.worktrees/\n", Encoding.UTF8);
        }

        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "add", "."]);
        commandRunner.Run("git", ["-C", paths.WorkingDirectory, "-c", "user.name=dotnet-forge", "-c", "user.email=dotnet-forge@localhost", "commit", "-m", "Initial dotnet-forge repository"]);
    }

    private void EnsureRuntimeIgnore(ProjectPaths paths)
    {
        var result = commandRunner.Run("git", ["-C", paths.WorkingDirectory, "rev-parse", "--git-path", "info/exclude"]);
        var excludeFile = Path.IsPathRooted(result.StandardOutput)
            ? result.StandardOutput
            : Path.Combine(paths.WorkingDirectory, result.StandardOutput);
        Directory.CreateDirectory(Path.GetDirectoryName(excludeFile)!);
        var existing = File.Exists(excludeFile) ? File.ReadAllLines(excludeFile).ToHashSet(StringComparer.Ordinal) : [];
        using var writer = File.AppendText(excludeFile);
        foreach (var line in new[] { ".swarmforge/", ".worktrees/" })
        {
            if (existing.Add(line))
            {
                writer.WriteLine(line);
            }
        }
    }

    private void PrepareWorktrees(EffectiveConfiguration configuration, ProjectPaths paths)
    {
        Directory.CreateDirectory(paths.WorktreesDirectory);
        foreach (var role in configuration.SelectedPack.Roles.Where(static role => role.Worktree is not "master" and not "none"))
        {
            var worktreePath = paths.WorktreePath(role.Worktree);
            if (Directory.Exists(Path.Combine(worktreePath, ".git")) || File.Exists(Path.Combine(worktreePath, ".git")))
            {
                continue;
            }

            commandRunner.Run("git", ["-C", paths.WorkingDirectory, "worktree", "add", "--force", "-B", $"dotnet-forge-{role.Worktree}", worktreePath, "HEAD"]);
        }
    }
}

public sealed class AgentLaunchCommandBuilder
{
    public string WritePromptFile(ProjectPaths paths, RuntimeRole role)
    {
        Directory.CreateDirectory(paths.PromptsDirectory);
        var promptFile = Path.Combine(paths.PromptsDirectory, $"{role.Role}.md");
        File.WriteAllText(
            promptFile,
            $"Read swarmforge/constitution.prompt, then read every file it refers to recursively, and obey all of those instructions.{Environment.NewLine}" +
            $"Read swarmforge/roles/{role.Role}.prompt, then read every file it refers to recursively, and follow all of those instructions.{Environment.NewLine}",
            Encoding.UTF8);
        return promptFile;
    }

    public string Build(RuntimeRole role, string promptFile)
    {
        var scriptsDirectory = Path.Combine(role.WorktreePath, "swarmforge", "scripts");
        var basePrefix =
            $"export DOTNET_FORGE_ROLE={Shell.Quote(role.Role)} && " +
            $"export SWARMFORGE_ROLE={Shell.Quote(role.Role)} && " +
            $"export PATH={Shell.Quote(scriptsDirectory)}:$PATH && " +
            $"cd {Shell.Quote(role.WorktreePath)} && ";
        var promptArgument = $"\"$(cat {Shell.Quote(promptFile)})\"";
        var displayName = Shell.Quote($"DotnetForge {role.DisplayName}");

        return role.Agent switch
        {
            "claude" => basePrefix + $"claude --append-system-prompt-file {Shell.Quote(promptFile)} --permission-mode acceptEdits -n {displayName} {promptArgument}",
            "codex" => basePrefix + $"codex -C {Shell.Quote(role.WorktreePath)} {promptArgument}",
            "copilot" => basePrefix + $"copilot -C {Shell.Quote(role.WorktreePath)} --name {displayName} -i {promptArgument}",
            "opencode" => basePrefix + $"opencode run {promptArgument}",
            "grok" => basePrefix + $"grok --cwd {Shell.Quote(role.WorktreePath)} --permission-mode acceptEdits --rules {promptArgument} --verbatim {promptArgument}",
            _ => throw new ForgeException($"Unsupported agent backend '{role.Agent}'.", 2),
        };
    }
}

public sealed class RunOrchestrator(
    EffectiveConfigurationService effectiveConfigurationService,
    PackMaterializer packMaterializer,
    WorkspacePreparationService workspacePreparationService,
    RuntimeStateStore runtimeStateStore,
    AgentLaunchCommandBuilder agentLaunchCommandBuilder,
    ICommandRunner commandRunner)
{
    public async Task<RunSummary> RunAsync(LaunchOptions options, CancellationToken cancellationToken = default)
    {
        var effectiveConfiguration = await effectiveConfigurationService.ResolveAsync(options, cancellationToken);
        var paths = ProjectPaths.For(effectiveConfiguration.WorkingDirectory);
        packMaterializer.Materialize(effectiveConfiguration);
        workspacePreparationService.Prepare(effectiveConfiguration);
        runtimeStateStore.Write(effectiveConfiguration);
        var runtimeRoles = runtimeStateStore.LoadRoles(effectiveConfiguration.WorkingDirectory);
        var executedCommands = new List<string>();

        if (!effectiveConfiguration.DryRun)
        {
            if (File.Exists(paths.StopFile))
            {
                File.Delete(paths.StopFile);
            }

            foreach (var role in runtimeRoles)
            {
                commandRunner.Run("tmux", ["-S", paths.TmuxSocket, "kill-session", "-t", role.Session], throwOnError: false);
                commandRunner.Run("tmux", ["-S", paths.TmuxSocket, "new-session", "-d", "-s", role.Session, "-n", "swarm"]);
                executedCommands.Add($"tmux -S {paths.TmuxSocket} new-session -d -s {role.Session} -n swarm");
            }

            var daemonCommand = $"dotnet-forge internal handoff-daemon --working-directory {Shell.Quote(effectiveConfiguration.WorkingDirectory)}";
            commandRunner.StartDetached("sh", ["-lc", daemonCommand], effectiveConfiguration.WorkingDirectory);
            executedCommands.Add(daemonCommand);

            var delay = effectiveConfiguration.ProjectConfiguration.AgentStartDelayMs;
            for (var index = 0; index < runtimeRoles.Count; index++)
            {
                var role = runtimeRoles[index];
                if (index > 0 && delay > 0)
                {
                    await Task.Delay(delay, cancellationToken);
                }

                var promptFile = agentLaunchCommandBuilder.WritePromptFile(paths, role);
                var command = agentLaunchCommandBuilder.Build(role, promptFile);
                commandRunner.Run("tmux", ["-S", paths.TmuxSocket, "send-keys", "-t", role.Session, command, "Enter"]);
                executedCommands.Add($"tmux -S {paths.TmuxSocket} send-keys -t {role.Session} {command} Enter");
            }

            if (effectiveConfiguration.Attach)
            {
                commandRunner.Run("tmux", ["-S", paths.TmuxSocket, "attach-session", "-t", runtimeRoles[0].Session]);
                executedCommands.Add($"tmux -S {paths.TmuxSocket} attach-session -t {runtimeRoles[0].Session}");
            }
        }
        else
        {
            foreach (var role in runtimeRoles)
            {
                var promptFile = agentLaunchCommandBuilder.WritePromptFile(paths, role);
                executedCommands.Add(agentLaunchCommandBuilder.Build(role, promptFile));
            }
        }

        return new RunSummary(effectiveConfiguration, paths, runtimeRoles, executedCommands);
    }
}

public sealed class StopOrchestrator(RuntimeStateStore runtimeStateStore, ICommandRunner commandRunner)
{
    public void Stop(string workingDirectory)
    {
        var paths = ProjectPaths.For(workingDirectory);
        Directory.CreateDirectory(Path.GetDirectoryName(paths.StopFile)!);
        File.WriteAllText(paths.StopFile, string.Empty, Encoding.UTF8);
        if (!File.Exists(paths.RolesFile))
        {
            return;
        }

        foreach (var role in runtimeStateStore.LoadRoles(workingDirectory))
        {
            commandRunner.Run("tmux", ["-S", paths.TmuxSocket, "kill-session", "-t", role.Session], throwOnError: false);
        }
    }
}
